project:
  type: website
  output-dir: _output
  render:
    - "*.qmd"
    - "!NOTES.md"

author: "Marco Willi"
affiliation: "Institute for Data Science I4DS, FHNW"

execute:
  freeze: auto

pdf-engine: xelatex

website:
  page-navigation: true
  title: "CAS Deep Learning - Computer Vision"
  description: "Homepage for CAS Deep Learning - Computer Vision (Part1) with reading materials and exercises"
  
  site-url: "https://marco-willi.github.io/cas-dl-compvis-lectures-hs2024/"
  repo-url: https://github.com/marco-willi/cas-dl-compvis-lectures-hs2024
  repo-actions: [issue]

  google-analytics: "G-SCHRGR3LNM"

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2024, Marco Willi"
    #background: "#D9E3E4"

  sidebar:
    logo: "/assets/logo.webp"
    pinned: true
    search: true
    align: center
    style: "docked"
    collapse-level: 1
    tools:
      - icon: github
        href: https://github.com/marco-willi/cas-dl-compvis-lectures-hs2024
        text: "GitHub organization"
      - icon: code-square

    contents:
      - text: "Home"
        href: index.qmd
      - section: Lectures
        contents:
          - pages/intro.qmd
          - pages/frameworks.qmd
          - pages/neural_networks.qmd
          - pages/cnns.qmd
          - pages/classification.qmd
          - pages/object_detection.qmd
          - pages/segmentation.qmd
          - pages/recent_advances.qmd
      - section: Slides
        contents:
          - slides_cas/intro.qmd
      - text: "Slides"
        href: pages/slides_cas.qmd
      # - section: Demos
      #   contents:
      #     - demos/pixelize.qmd
      - text: "Exercises"
        href: pages/exercises.qmd
      - section: Demos
        contents:
          - demos/cross_entropy.qmd
          - demos/clip.qmd
      - text: "Mini Projects"
        href: pages/mini_projects.qmd
      - section: Resources
        contents:
          - pages/literature.qmd
          - pages/links.qmd
          - pages/notation.qmd

bibliography: assets/references.bib

institute: "Institute for Data Science I4DS, FHNW"

format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    code-fold: false
    code-tools: true
    highlight-style: github
    # include-in-header:
    #    - "_dollar.tex"
    #    - "_macros.tex"
    #    - "_dollar.tex"
  pdf:
    include-in-header:
       - "./assets/_macros.tex"