# Willkommen zum Modul Computer Vision mit Deep Learning

 Herzlich willkommen zum Modul **Computer Vision mit Deep Learning** (1. Teil)!
 
 Hier finden Sie Unterlagen und aktuelle Informationen zum Modul.
 
 [Modul Page](https://www.fhnw.ch/de/weiterbildung/technik/computer-vision-mit-deep-learning)

 [CAS Page](https://www.fhnw.ch/de/weiterbildung/technik/cas-deep-learning)


## Inhalte


### Tag 1 - Grundlagen Convolutional Neural Networks

| Zeit | Thema |
|------|--------|
|8:45 - 9:30	| Einführung Computer Vision mit Deep Learning
|9:30 - 10:30 	| Übung: Deep Learning für Bilder
|10:30  - 10:45	| Pause
|10:45 - 12:00	| Convolutional Neural Networks
|12:00 - 13:00	| Mittagspause
|13:00 - 16:30	| Übung: CNNs für Bildklassifikation


### Tag 2 - Bildklassifikation und Anwendungen

| Zeit | Thema |
|------|--------|
|8:45 - 9:30	| Recap & Quizz
|9:30 - 10:30 	| Theorie: Praktische Überlegungen
|10:30  - 10:45	| Pause
|10:45 - 11:30	| ...
|11:30 - 12:15	| ....
|12:15 - 13:15	| Mittagspause
|13:15 - 15:30	| Übung: Bildklassifikation
|15:30 - 16:30	| Foundation Models


<!-- 
| Datum | Thema                                               | Übung     
|-----------------|-----------------------------------------------------|----------------------|
| 09 - 1.11.2024 | Einführung in Deep Learning für Computer Vision     | PyTorch Intro
| 10 - 2.11.2024 | Convolutional Neural Networks                       | Neural Networks / CNNs
           -->

## Lernziele

- Bildklassifikation vertieft verstehen
- Methoden implementieren, anwenden und interpretieren können
- Mit Deep Learning Frameworks umgehen und Libraries verwenden können
- Praktische Anwendung von Deep Learning Modellen demonstrieren und vorstellen können

