on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:

  create-envfile:
    runs-on: ubuntu-18.04
    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_SEMESTER_TAG: hs2024
        envkey_IMAGE_TAG: v20240717
        envkey_REPO_NAME: cas-dl-compvis-lectures-hs2024
        envkey_REGISTRY_ROOT: mwilli13
        envkey_CONTAINER_REGISTRY_PUSH_TOKEN:
        envkey_CONTAINER_REGISTRY_USER:
        envkey_TEXINPUTS: ".:~/work/book/slides:"
        file_name: .env

  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

      - uses: cardinalby/export-env-action@v1
        with:
          envFile: '.env'    
          expand: 'true'
        
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}