on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        working-directory: ./quarto_webpage
        uses: actions/checkout@v4

      - name: Set up Quarto
        working-directory: ./quarto_webpage
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        working-directory: ./quarto_webpage
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}